/**
 * promo-9-9 — loader for the time-boxed "9.9 COLLECTION" promo.
 *
 * Isolated from products.db / live_products_export.json: this file only
 * carries { sku, promoPrice, regularPrice, discountPct } pairs generated by
 * scripts/gen-9-9-collection.mjs from two source CSVs. Product identity
 * (name, image, stock) is always read live via getProductBySku — never
 * duplicated here — so the promo page reflects current catalog state.
 *
 * DEFENSIVE, mirrors lib/collections.ts: returns null / false rather than
 * throwing when data/promo_9_9_collection.json is absent or malformed, so
 * a deploy before the generator has run (or after the file is deleted once
 * the promo is over) never breaks /collections.
 */
import fs from 'fs';
import path from 'path';

export interface Promo99Item {
  sku: string;
  promoPrice: number;
  regularPrice: number;
  discountPct: number;
}

export interface Promo99Collection {
  slug: string;
  name: string;
  tagline: string;
  promoEndDate: string; // ISO 8601, includes explicit UTC offset
  items: Promo99Item[];
}

function promoPath(): string | null {
  const candidates = [
    path.join(process.cwd(), 'data', 'promo_9_9_collection.json'),             // cwd = repo root
    path.join(process.cwd(), '..', '..', 'data', 'promo_9_9_collection.json'), // cwd = apps/catalog
  ];
  return candidates.find((p) => fs.existsSync(p)) ?? null;
}

let _promo: Promo99Collection | null | undefined; // undefined = not yet loaded

function load(): Promo99Collection | null {
  if (_promo !== undefined) return _promo;
  const file = promoPath();
  if (!file) { _promo = null; return _promo; }
  try {
    const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (!raw || typeof raw !== 'object' || !Array.isArray(raw.items)) {
      _promo = null;
    } else {
      _promo = raw as Promo99Collection;
    }
  } catch {
    _promo = null;
  }
  return _promo;
}

/** The promo collection, or null if not yet generated / malformed. */
export function getPromo99(): Promo99Collection | null {
  return load();
}

/** True iff the promo file loaded successfully AND `now` is before promoEndDate. */
export function isPromo99Active(now: Date = new Date()): boolean {
  const promo = load();
  if (!promo) return false;
  return now.getTime() < new Date(promo.promoEndDate).getTime();
}
