# -*- coding: utf-8 -*-
"""
links.py — real product URLs and base images.

SOURCE OF TRUTH: Supabase `products.magento_item_url` / `products.image_url`.
The old winenow-base-images-*.csv export is now a FALLBACK only.

Why the switch
  The CSV was a hand-uploaded Wine-Now store-view export with three standing
  problems: 14 rows carried an unquoted comma inside item_name that shifted
  every later column (hence the parse-from-the-right hack below, kept for the
  fallback path), it had to be re-exported and re-uploaded by hand every
  session, and it went stale silently. Supabase carries the same values —
  verified on a 251-SKU overlap against the live pages: 248 identical, and 2 of
  the 3 differences were errors in the comparison set, not in Supabase.
  Coverage is 6,352 URLs and 6,387 images across 6,388 active products.

  The handful of SKUs that fell back to catalogsearch under the CSV still fall
  back here (WRW1570BN, WRW6216FS, LWH0162BU, LWH0164BU, WWW5371AB, WWW5372AB):
  their magento_item_url is null in the catalog. That is a gap to fix in
  Magento, not an export problem, and no reader can close it.

REFRESHING THE CACHE
  The build sandbox cannot reach Supabase — only an assistant session with the
  MCP connector can. So the cache is a file, regenerated by running the query
  below against project dsyplzckfezcxiuikkfm and saving the output as
  links_cache.tsv (one `sku|slug|image` per line, under a `# generated:` header).

  Batch the SKU list in groups of ~280 or the result is truncated.

    with s as (select unnest(string_to_array('<SKU,SKU,...>', ',')) as sku)
    select string_agg(
      p.sku || '|' ||
      coalesce(replace(p.magento_item_url, 'https://th.wine-now.com/', ''), '') || '|' ||
      coalesce(
        case when split_part(p.image_url,'/',7) = left(split_part(p.image_url,'/',9),1)
              and split_part(p.image_url,'/',8) = substr(split_part(p.image_url,'/',9),2,1)
             then split_part(p.image_url,'/',9)
             else '*' || replace(p.image_url,
                                 'https://th.wine-now.com/media/catalog/product/', '')
        end, ''),
      E'\n' order by p.sku)
    from products p join s on s.sku = p.sku;

  The SKU list is every SKU the build touches — `python3 needed_skus.py`.

  Storage note: the image is stored as a bare filename because Magento shards
  media by the first two characters of that filename. One product in 6,387
  breaks the convention, so a token prefixed with `*` is a literal path under
  media/catalog/product/ and is used as-is.

HOSTS
  Magento shares url_key across store views, verified against live indexed
  pages, so an L-prefix SKU is served from th.liq9.asia and everything else
  from th.wine-now.com. Both sources store the Wine-Now host; we swap it.
"""
import csv, glob, os, re, datetime

CACHE     = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'links_cache.tsv')
CSV_GLOB  = os.environ.get('WNLQ9_LINKS_CSV_GLOB', os.path.join(
    os.path.dirname(os.path.abspath(__file__)), 'winenow-base-images-*.csv'))
SUPP      = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'links_supplement.csv')
MEDIA     = 'https://th.wine-now.com/media/catalog/product/'

SPIRIT_HOST = 'th.liq9.asia'
WINE_HOST   = 'th.wine-now.com'

SOURCE  = None     # 'supabase-cache' | 'csv-export' | 'none'
AS_OF   = None     # date the source was generated, read by the freshness gate


def _img_url(token):
    """Expand a stored image token into a full media URL."""
    if not token:
        return ''
    if token.startswith('*'):
        return MEDIA + token[1:]
    return f'{MEDIA}{token[0]}/{token[1]}/{token}'


def load_cache(path=CACHE):
    """Primary path: the Supabase-derived cache."""
    global SOURCE, AS_OF
    out = {}
    with open(path, encoding='utf-8') as fh:
        for line in fh:
            line = line.rstrip('\n')
            if not line:
                continue
            if line.startswith('#'):
                m = re.search(r'generated:\s*(\d{4}-\d{2}-\d{2})', line)
                if m:
                    AS_OF = m.group(1)
                continue
            parts = line.split('|')
            if len(parts) != 3:
                continue
            sku, slug, img = parts
            out[sku.strip()] = {'url': f'https://{WINE_HOST}/{slug}' if slug else '',
                                'img': _img_url(img),
                                'name': '', 'sites': ''}
    if AS_OF is None:                       # no header — fall back to file mtime
        AS_OF = datetime.date.fromtimestamp(os.path.getmtime(path)).isoformat()
    SOURCE = 'supabase-cache'
    return out


def load_csv(path=None):
    """Fallback path: the old store-view export.

    Parses from the RIGHT because 14 rows carry an unquoted comma inside
    item_name, which shifts every column after it. sku is always first,
    item_url always last. Any new reader of that file must do the same.
    """
    global SOURCE, AS_OF
    if path is None:
        files = sorted(glob.glob(CSV_GLOB), key=os.path.getmtime)
        if not files:
            return {}
        path = files[-1]
    out = {}
    with open(path, encoding='utf-8-sig', newline='') as fh:
        rd = csv.reader(fh)
        next(rd, None)
        for row in rd:
            if len(row) < 5:
                continue
            url = row[-1].strip()
            img = row[-2].strip()
            out[row[0].strip()] = {
                'url':   url if url.startswith('http') else '',
                'img':   img if img.startswith('http') else '',
                'name':  ','.join(row[1:-3]).strip(),
                'sites': row[-3].strip()}
    SOURCE = 'csv-export'
    AS_OF = datetime.date.fromtimestamp(os.path.getmtime(path)).isoformat()
    return out


def load():
    """Supabase cache is authoritative; the CSV export SUPPLEMENTS it.

    The two are merged rather than one replacing the other, because they fail
    in opposite directions. Measured on the 820 SKUs this build touches:

      Supabase wins  3 SKUs whose image the CSV was missing (LWH0162BU,
                     LWH0164BU), and corrects LTQ0001AD, where the CSV still
                     carried the 700 ml slug for a bottle the catalog now
                     records as 750 ml.
      CSV wins       8 SKUs. Six of them — WRW5835AF, WRW6041HR, WSP9035AB,
                     WSP9046WN, WWW6325WN, WWW6326WN — are absent from the
                     `products` table altogether while being live in Magento,
                     which is the missing catalog sync showing through. The
                     other two, WWW5371AB and WWW5372AB, are in the table with
                     a null URL and a TAB embedded in `name`
                     ("Nollen Erben\t Mosel Riesling Spatlese") — the same
                     delimiter-inside-item_name bug that breaks the CSV, frozen
                     into the database at import time.

    So per SKU: take Supabase, fall back to the export for anything it lacks.
    Once the products sync exists, the export can be dropped entirely.
    """
    global SOURCE
    cache = load_cache() if os.path.exists(CACHE) else {}
    cache_as_of = AS_OF
    supp = load_csv()
    if not supp and os.path.exists(SUPP):
        # No full export this session — use the checked-in stopgap covering only
        # the SKUs Supabase is missing. Delete it once the products sync exists.
        supp = load_csv(SUPP)
    if cache:
        filled = 0
        for sku, r in supp.items():
            if sku not in cache or not cache[sku]['url']:
                if r.get('url'):
                    cache.setdefault(sku, {'url': '', 'img': '', 'name': '', 'sites': ''})
                    cache[sku]['url'] = r['url']
                    cache[sku]['img'] = cache[sku].get('img') or r.get('img', '')
                    filled += 1
        SOURCE = f'supabase-cache (+{filled} from csv export)' if filled else 'supabase-cache'
        globals()['AS_OF'] = cache_as_of
        return cache
    if supp:
        return supp
    SOURCE = 'none'
    return {}


LINKS = load()


def host_for(sku):
    """Spirits live on LIQ9, everything else (wine, barware, mixers) on Wine-Now."""
    return SPIRIT_HOST if sku[:1] == 'L' else WINE_HOST


def product_url(sku, fallback_host=None):
    """Real product page on the correct storefront, else a catalogsearch fallback."""
    host = fallback_host or host_for(sku)
    r = LINKS.get(sku)
    if r and r['url']:
        return re.sub(r'^https://[^/]+', f'https://{host_for(sku)}', r['url'])
    return f'https://{host}/catalogsearch/result/?q={sku}'


def product_image(sku, current=None):
    """Catalog base image. Prefers the cache, keeps whatever we already had otherwise."""
    r = LINKS.get(sku)
    if r and r['img']:
        return r['img']
    return current


def coverage(skus):
    real = sum(1 for s in skus if LINKS.get(s, {}).get('url'))
    return real, len(skus) - real
